server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: mecanica-gestor-api
  datasource:
    url: jdbc:postgresql://localhost:5433/mecanica_gestor_api
    username: postgres
    password: 102030
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect