server:
  port: 5001
  servlet:
    context-path: /api
spring:
  application:
    name: mecanica-gestor-api
  datasource:
    url: ${POSTGRESQL_HOST}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASS}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

# noinspection undefined
api:
  cors:
    allowed-origins: ${API_CORS_ALLOWED_ORIGINS}
  security:
    secret: ${API_SECRET}

# noinspection undefined
rabbitmq:
  queue:
    criar-oficina: rabbitmq-queue-novas-oficina