INSERT INTO clientes (cpf_cnpj, razao, nm_completo, tipo) VALUES ('00000000000', 'CONSUMIDOR', 'CONSUMIDOR', 'PF') on conflict do nothing;

INSERT INTO marcas (nome, logo) VALUES
    ('Aston Martin','https://www.autoo.com.br/img/aston-martin.png'),
    ('Audi','https://www.autoo.com.br/img/audi.png'),
    ('BMW','https://www.autoo.com.br/img/bmw.png'),
    ('BYD','https://www.autoo.com.br/img/byd.png'),
    ('CAOA Chery','https://www.autoo.com.br/img/caoa_chery.png'),
    ('Chevrolet','https://www.autoo.com.br/img/chevrolet.png'),
    ('Citroën','https://www.autoo.com.br/img/citroen.png'),
    ('Effa','https://www.autoo.com.br/img/effa.png'),
    ('Ferrari','https://www.autoo.com.br/img/ferrari.png'),
    ('Fiat','https://www.autoo.com.br/img/fiat.png'),
    ('Ford','https://www.autoo.com.br/img/ford.png'),
    ('Foton','https://www.autoo.com.br/img/foton.png'),
    ('GWM','https://www.autoo.com.br/img/gwm.png'),
    ('Honda','https://www.autoo.com.br/img/honda.png'),
    ('Hyundai','https://www.autoo.com.br/img/hyundai.png'),
    ('Iveco','https://www.autoo.com.br/img/iveco.png'),
    ('JAC','https://www.autoo.com.br/img/jac.png'),
    ('Jaecoo','https://www.autoo.com.br/img/jaecoo.png'),
    ('Jaguar','https://www.autoo.com.br/img/jaguar.png'),
    ('Jeep','https://www.autoo.com.br/img/jeep.png'),
    ('Kia','https://www.autoo.com.br/img/kia.png'),
    ('Lamborghini','https://www.autoo.com.br/img/lamborghini.png'),
    ('Land Rover','https://www.autoo.com.br/img/land_rover.png'),
    ('Lexus','https://www.autoo.com.br/img/lexus.png'),
    ('Maserati','https://www.autoo.com.br/img/maserati.png'),
    ('McLaren','https://www.autoo.com.br/img/mclaren.png'),
    ('Mercedes-AMG','https://www.autoo.com.br/img/mercedes-amg.png'),
    ('Mercedes-Benz','https://www.autoo.com.br/img/mercedes-benz.png'),
    ('Mini','https://www.autoo.com.br/img/mini.png'),
    ('Mitsubishi','https://www.autoo.com.br/img/mitsubishi.png'),
    ('Neta','https://www.autoo.com.br/img/neta.png'),
    ('Nissan','https://www.autoo.com.br/img/nissan.png'),
    ('Omoda','https://www.autoo.com.br/img/omoda.png'),
    ('Peugeot','https://www.autoo.com.br/img/peugeot.png'),
    ('Porsche','https://www.autoo.com.br/img/porsche.png'),
    ('RAM','https://www.autoo.com.br/img/ram.png'),
    ('Renault','https://www.autoo.com.br/img/renault.png'),
    ('Riddara','https://www.autoo.com.br/img/riddara.png'),
    ('Rolls-Royce','https://www.autoo.com.br/img/rolls-royce.png'),
    ('Seres','https://www.autoo.com.br/img/seres.png'),
    ('Subaru','https://www.autoo.com.br/img/subaru.png'),
    ('Suzuki','https://www.autoo.com.br/img/suzuki.png'),
    ('Toyota','https://www.autoo.com.br/img/toyota.png'),
    ('Volkswagen','https://www.autoo.com.br/img/volkswagen.png'),
    ('Volvo','https://www.autoo.com.br/img/volvo.png'),
    ('Zeekr','https://www.autoo.com.br/img/zeekr.png'),
    ('Amazon','https://www.motoo.com.br/img/amazon.png'),
    ('Avelloz','https://www.motoo.com.br/img/avelloz.png'),
    ('Bajaj','https://www.motoo.com.br/img/bajaj.png'),
    ('BMW','https://www.motoo.com.br/img/bmw.png'),
    ('BRP','https://www.motoo.com.br/img/brp.png'),
    ('Bull','https://www.motoo.com.br/img/bull.png'),
    ('CFMoto','https://www.motoo.com.br/img/cfmoto.png'),
    ('Dafra','https://www.motoo.com.br/img/dafra.png'),
    ('Ducati','https://www.motoo.com.br/img/ducati.png'),
    ('Fever','https://www.motoo.com.br/img/fever.png'),
    ('Haojue','https://www.motoo.com.br/img/haojue.png'),
    ('Harley-Davidson','https://www.motoo.com.br/img/harley-davidson.png'),
    ('Honda','https://www.motoo.com.br/img/honda.png'),
    ('Husqvarna','https://www.motoo.com.br/img/husqvarna.png'),
    ('Kawasaki','https://www.motoo.com.br/img/kawasaki.png'),
    ('KTM','https://www.motoo.com.br/img/ktm.png'),
    ('Kymco','https://www.motoo.com.br/img/kymco.png'),
    ('Leva','https://www.motoo.com.br/img/leva.png'),
    ('LL Motors','https://www.motoo.com.br/img/ll_motors.png'),
    ('Motocar','https://www.motoo.com.br/img/motocar.png'),
    ('Motorino','https://www.motoo.com.br/img/motorino.png'),
    ('Mottu','https://www.motoo.com.br/img/mottu.png'),
    ('Niu','https://www.motoo.com.br/img/niu.png'),
    ('Origem','https://www.motoo.com.br/img/origem.png'),
    ('Piaggio','https://www.motoo.com.br/img/piaggio.png'),
    ('Royal Enfield','https://www.motoo.com.br/img/royal_enfield.png'),
    ('Shineray','https://www.motoo.com.br/img/shineray.png'),
    ('Sousa','https://www.motoo.com.br/img/sousa.png'),
    ('Suzuki','https://www.motoo.com.br/img/suzuki.png'),
    ('Traxx','https://www.motoo.com.br/img/traxx.png'),
    ('Triumph','https://www.motoo.com.br/img/triumph.png'),
    ('Vespa','https://www.motoo.com.br/img/vespa.png'),
    ('Vmoto','https://www.motoo.com.br/img/vmoto.png'),
    ('Voltz','https://www.motoo.com.br/img/voltz.png'),
    ('Watts','https://www.motoo.com.br/img/watts.png'),
    ('Yamaha','https://www.motoo.com.br/img/yamaha.png'),
    ('Zontes','https://www.motoo.com.br/img/zontes.png')
ON CONFLICT DO NOTHING;
